---
output:
  html_document:
    df_print: paged
    fig.align: center
    self_contained: yes 
    fig.height: 4
    fig.width: 8
    theme: united
    toc: yes
    toc_depth: 4
    toc_float: yes
    number_sections: yes
    code_folding: hide
title: "Auswertung TC Daten"
author: "David Lilek"
date: "`r format(Sys.time(), '%d %B %Y, %X')`"
editor_options: 
  markdown: 
    wrap: 72
---


# Load Libraries & Plot function & Colors

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(UpSetR)
library(pheatmap)
library(ggvenn)
library(knitr)
library(reshape2)
library(eulerr)
#library(venneuler)
#library(VennDiagram) 
```

```{r}
euler_venn_2comp <- function(lst, label_venn, color_venn, cex_venn, grid, gList, h_just, v_just) {
  ######################################
  #################plot 2 venn diagrams
  ######################################
  p<-plot(euler(lst),
          input="union",
          shape="ellipse",
          quantities=list(type = c("percent", 'counts'),
                          cex = cex_venn), #schriftgröße für A, B bzw intersection
          key=TRUE,
          labels=FALSE,
          lty = c(1,1),
          legend = list(labels = label_venn,
                        side = "bottom",
                        nrow = 1, ncol = 3),
          edges=TRUE,
          fills = color_venn, #color für A,B bzw intersection 
          alpha=0.8)
  # https://stackoverflow.com/questions/75177293/how-to-change-the-label-position-when-plotting-venn-diagram-from-eulerr-package
  tags <- p$children[[2]]$children[[1]]$children$tags$children
  tags <- do.call(grid::gList, lapply(tags, function(x) {
    x$children[[2]]$label <- sub(" \\(", "\n(", x$children[[2]]$label)
    x$children[[2]]$just <- NULL
    x$children[[2]]$hjust <- h_just
    x$children[[2]]$vjust <- v_just
    x}))
  
  p$children[[2]]$children[[1]]$children$tags$children <- tags
  print(p)
}


euler_venn_3comp <- function(lst, cex_venn, label_venn, color_venn, grid, gList, h_just, v_just) {
  ##################################
  ###### venn diagram 3 comparisons
  ##################################
  p<-plot(euler(lst),
          input="union",
          shape="ellipse",
          quantities=list(type = c("percent", 'counts'),
                          cex = cex_venn), #schriftgröße für A, B, C bzw intersection
          key=TRUE,
          labels=FALSE,
          lty = c(1,1,1),
          legend = list(labels = label_venn,
                        side = "bottom",
                        nrow = 1, ncol = 3),
          edges=TRUE,
          fills = color_venn, #color für A,B bzw intersection fills = grey[c(10,18,25)]
          alpha=0.8)
  # https://stackoverflow.com/questions/75177293/how-to-change-the-label-position-when-plotting-venn-diagram-from-eulerr-packages
  tags <- p$children[[2]]$children[[1]]$children$tags$children
  tags <- do.call(grid::gList, lapply(tags, function(x) {
    x$children[[2]]$label <- sub(" \\(", "\n(", x$children[[2]]$label)
    x$children[[2]]$just <- NULL
    x$children[[2]]$hjust <- h_just
    x$children[[2]]$vjust <- v_just
    x}))
  
  p$children[[2]]$children[[1]]$children$tags$children <- tags
  print(p)
}

```

```{r}
#get colors
#total protein extract
total <- rgb(255,93,93, maxColorValue = 255)
#fractions high MW SEC
highMW <- rgb(169,208,142,maxColorValue = 255)
#fractions low MW SEC
lowMW <- rgb(255,217,102, maxColorValue = 255)
#in-gel digest
IG <- rgb(180,198,231,maxColorValue = 255)
```


# AIO - PHO-P - PHO-P-U

* hier wurde die all in one extraktion mit D1 (PHO-P) und D2 (PHO-P-U) verglichen
* D1 und D2 wurden gemerged und sind im Diagramm als PHO bzw 2D bezeichnet dargestellt


```{r message=FALSE, warning=FALSE}
res_raw <- readRDS(file = "results_v002/results_run1_mqpar_extracts_2gether_200520_reanalysisCM_LFQ_combined_txt_proteinGroups.txt_Unique.RDS")
res_raw <- res_raw[[1]]

res <- res_raw[,-ncol(res_raw)]
res <- res*1

AIO <- apply(res[,c(1:3)], 1, any)
PHO <- apply(res[,c(4:9)],1,any)
fasta <- c()
for (i in 1:length(res_raw$FASTA)){
  tmp <- strsplit(res_raw$FASTA[i],split='\\|')[[1]][2]
  fasta <- c(fasta,tmp)
}

res_clear <- as.data.frame(cbind(AIO,PHO,fasta))

res_clear$AIO <- as.logical(res_clear$AIO)
res_clear$PHO <- as.logical(res_clear$PHO)
res_clear <- res_clear[,-3]*1
res_clear[res_clear==0] <- NA



proteins <- as.data.frame(which(!is.na(res_clear), arr.ind=TRUE))

AIO <- proteins %>% dplyr::filter(col == 1)
PHO <- proteins %>% dplyr::filter(col == 2)

# combine to list
lst <- list("2D"=as.double(PHO[,1]),
            "AIO"=as.double(AIO[,1]))




#venn digarams
#get colors
AIO_col <- rgb(255,93,93, maxColorValue = 255)
PHO_col <- rgb(169,208,142,maxColorValue = 255)


euler_venn_2comp(lst, label_venn = c("2D","AIO"), color_venn = c(PHO_col,AIO_col), cex_venn = c(1,0.8,1), h_just = 0.5, v_just = 0.5)


print(c("AIO","PHO"))
sum(res_clear$AIO,na.rm = TRUE)
sum(res_clear$PHO,na.rm = TRUE)
```

## Vergleich PHO-P/PHO-P-U mit E4_D1/D2

* hier wurde PHO-P mit PHO-P-U zu PHO gemerged und mit E4_D1/D2 verglichen

```{r message=FALSE, warning=FALSE}

D1_raw <- readRDS(file = "results_v002/results_run1_mqpar_extracts_2gether_E4_D1_a-j_LFQ_combined_txt_proteinGroups.txt_Unique.RDS")
D1_raw <- D1_raw[[1]]
D1 <- dplyr::select(D1_raw, contains("Pool"))
D1 <- apply(D1, 1, any)
#D1 <- as.data.frame(cbind(D1, D1_raw$FASTA))
fasta <- c()
for (i in 1:length(D1_raw$FASTA)){
  tmp <- strsplit(D1_raw$FASTA[i],split='\\|')[[1]][2]
  fasta <- c(fasta,tmp)
}
D1 <- as.data.frame(cbind(D1, fasta))
D2_raw <- readRDS(file = "results_v002/results_run1_mqpar_extracts_2gether_D2_LFQ_combined_txt_proteinGroups.txt_Unique.RDS")
D2_raw <- D2_raw[[1]]
D2 <- dplyr::select(D2_raw, contains("Gesamt"))
D2 <- apply(D2, 1, any)
fasta <- c()
for (i in 1:length(D2_raw$FASTA)){
  tmp <- strsplit(D2_raw$FASTA[i],split='\\|')[[1]][2]
  fasta <- c(fasta,tmp)
}
#D2 <- as.data.frame(cbind(D2, D2_raw$FASTA))
D2 <- as.data.frame(cbind(D2, fasta))
comp  <- merge(D1, D2,
                           all = TRUE,
                           by = "fasta")
comp$D1 <- as.logical(comp$D1)
comp$D2 <- as.logical(comp$D2)
E4 <- apply(comp[,c(2:3)], 1, any)
E4 <- as.data.frame(cbind(comp$fasta,E4))
colnames(E4) <- c("fasta","E4")

res_raw <- readRDS(file = "results_v002/results_run1_mqpar_extracts_2gether_200520_reanalysisCM_LFQ_combined_txt_proteinGroups.txt_Unique.RDS")
res_raw <- res_raw[[1]]

res <- res_raw[,-ncol(res_raw)]
res <- res*1

AIO <- apply(res[,c(1:3)], 1, any)
PHO <- apply(res[,c(4:9)],1,any)
fasta <- c()
for (i in 1:length(res_raw$FASTA)){
  tmp <- strsplit(res_raw$FASTA[i],split='\\|')[[1]][2]
  fasta <- c(fasta,tmp)
}

res_clear <- as.data.frame(cbind(PHO,fasta))

comp <- merge(E4, res_clear,
              all = TRUE,
              by = "fasta")

comp$E4 <- as.logical(comp$E4)
comp$PHO <- as.logical(comp$PHO)
comp <- comp[,-1]*1
comp[comp==0] <- NA



proteins <- as.data.frame(which(!is.na(comp), arr.ind=TRUE))

E4 <- proteins %>% dplyr::filter(col == 1)
PHO <- proteins %>% dplyr::filter(col == 2)

# combine to list
lst <- list("E4"=as.double(E4[,1]),
            "PHO"=as.double(PHO[,1]))



#venn digarams
#get colors
E4 <- rgb(255,93,93, maxColorValue = 255)
PHO <- rgb(169,208,142,maxColorValue = 255)


euler_venn_2comp(lst, label_venn = c("E4","PHO"), color_venn = c(E4,PHO), cex_venn = c(1,1), h_just = 0.5, v_just = 0.5)

```




# CAR-CIT-PHOS



```{r message=FALSE, warning=FALSE}
res_raw <- readRDS(file = "results_v002/mqpar_extracts_2gether_reanalysisCM_extraktejakob_proteinGroups.txt_Unique.RDS")
res_raw <- res_raw[[1]]


res <- res_raw[,-ncol(res_raw)]
res <- res*1

CAR <- apply(res[,c(1:2)], 1, any)
CIT <- apply(res[,c(3:4)],1,any)
PHOS <- apply(res[,c(5:6)],1,any)

fasta <- c()
for (i in 1:length(res_raw$FASTA)){
  tmp <- strsplit(res_raw$FASTA[i],split='\\|')[[1]][2]
  fasta <- c(fasta,tmp)
}

res_clear <- as.data.frame(cbind(CAR,CIT,PHOS,fasta))

res_clear$CAR <- as.logical(res_clear$CAR)
res_clear$CIT <- as.logical(res_clear$CIT)
res_clear$PHOS <- as.logical(res_clear$PHOS)
res_clear <- res_clear[,-4]*1
res_clear[res_clear==0] <- NA



proteins <- as.data.frame(which(!is.na(res_clear), arr.ind=TRUE))

CAR <- proteins %>% dplyr::filter(col == 1)
CIT <- proteins %>% dplyr::filter(col == 2)
PHOS <- proteins %>% dplyr::filter(col == 3)

# combine to list
lst <- list("CAR"=as.double(CAR[,1]),
            "CIT"=as.double(CIT[,1]),
            "PHOS"=as.double(PHOS[,1]))



#venn digarams
#get colors
col1 <- rgb(255,93,93, maxColorValue = 255)
#fractions high MW SEC
col2 <- rgb(169,208,142,maxColorValue = 255)
#fractions low MW SEC
col3 <- rgb(255,217,102, maxColorValue = 255)

euler_venn_3comp(lst, label_venn = c("CAR","CIT","PHOS"), color_venn = c(col1,col2,col3), cex_venn = c(1,1), h_just = 0.5, v_just = 0.5)


print(c("CAT","CIT","PHOS"))
sum(res_clear$CAR,na.rm = TRUE)
sum(res_clear$CIT,na.rm = TRUE)
sum(res_clear$PHOS,na.rm = TRUE)
```
